name: mi_card
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/me.jpg
  fonts:
    - family: GreatVibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf

    - family: ArefRuqaa
      fonts:
        - asset: fonts/ArefRuqaa-Bold.ttf

    - family: Gabriela
      fonts:
        - asset: fonts/Gabriela-Regular.ttf
